version: '2.2'

services:
  bot:
    build: .
    command: python main.py
    tty: true
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/postgres
      - REDIS_URL=redis://redis:6379

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:alpine
