version: '2.2'

services:
  bot:
    build: .
    command: python main.py
    tty: true
    volumes:
    - .:/app
    depends_on:
      - bot-db
    environment:
      - DATABASE_URL=postgresql://postgres@bot-db/postgres

  bot-db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
