"""empty message

Revision ID: 2d1cb7c1b04e
Revises: fd50ff8ad8e2
Create Date: 2021-07-27 09:28:24.056600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d1cb7c1b04e'
down_revision = 'fd50ff8ad8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jigasya_members',
                  sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jigasya_members', 'birth_date')
    # ### end Alembic commands ###
