"""empty message

Revision ID: 38cc3398b65e
Revises: 2d1cb7c1b04e
Create Date: 2021-08-04 19:07:32.872174

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '38cc3398b65e'
down_revision = '2d1cb7c1b04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jigasya_members',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jigasya_members', 'updated_at')
    # ### end Alembic commands ###
